# numpy 入门

In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(f'numpy shap 查看当前数据形状 {arr.shape}')

array = np.array([[1,2,3, 4], [4,5,6, 7], [7,8,9,10]])

print(array.shape)

# 使用 ndmin 参数，指定当前数据最小维度
arr = np.array([1,2,3,4,5,6], ndmin=3)
print(arr)



numpy shap 查看当前数据形状 (6,)
[[[1 2 3 4 5 6]]]


In [8]:
''' 
    numpy arange(start, stop, step, dtype)
    start   开始值
    stop    终止值
    step    步长
    dtype   元素类型
'''

arr = np.arange(1, 10, 2, dtype=float)
print(arr)

[1. 3. 5. 7. 9.]


In [14]:
''' 
    random(size)
    size    接受一个元组，表示生成 ndarry的形状
'''
arr = np.random.random(size=(3,))
print(arr)
arr=np.random.randint(1,5, size=(3,2))
print(arr)

[0.76901959 0.20224632 0.20667656]
[[2 3]
 [4 3]
 [3 2]]


In [25]:
'''
    切片， 开始从0
        一维数组[开始:结束:步长]
        二维数组[(行)开始:结束:步长, (列)开始:结束:步长]

'''

arr = np.arange(12)
arr = arr.reshape(4, 3)
print(arr)
# 使用切片取出 4，5，7, 8元素

arr = arr[1:3, 1:3]
print(arr)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
